const timeLineConstantMessage = {
    TIMELINE_CREATION_SUCCESSFULLY :"Time line created successfully",
    TIMELINE_CREATION_FAILED :"Time line created failed",
    TIMELINE_INTERNAL_SERVER_ERROR:"Internal Server Error",
    TIMELINES_LISTING_FAILED:"Timeline Listing failed",
    TIMELINES_LISTED_SUCCESSFULLY:"Timeline listing succeessfully",
    TIMELINE_UPDATED_SUCCESSFULLY:"Time line updated successfully",
    TIMELINE_UPDATED_FAILED:"Time line updated failes",
    TIMELINE_DELETED_SUCCESSFULLY:"Time line deleted successfully",
    TIMELINE_DELETED_FAILED:"Time line deleted failed",
    TIMELINE_NOT_FOUND:"Time line not found",
    USER_LIKE_THIS_TIMELINE : "User like this timeline",
    USER_UNLIKE_THIS_TIMELINE:"User unlike this timeline",
    SHUFFLE:"shuffle",
    MOST_LIKED:"mostLiked",
    NEWEST_TO_OLDEST: "NewestTooldest",
    LIKED_USERS_FETCHED_SUCCESSFULLY:"Liked user fetched successfully",    
    LIKED_USERS_FETCHED_FAIL:"This User has not created this timeline. Pre-Condition Failed",
    YOU_ARE_BLOCKED:"You are blocked you are not able to access this Timeline",
    TIMELINE_REPORT_CREATED:"Timeline report created",
    TIMELINE_REPORT_FAILED:"Timeline report failed",
    REPORT_TIMELINE_FETCH_SUCCESSFULLY :"Report timeline fetch successfully",
    REPORT_TIMELINE_FETCH_FAILED:"Report timeline fetch failed",
}
export default timeLineConstantMessage