const userConstantMessages = {
    EDIT_PROFILE_SUCCESS: "Your profile is updated successfully.",
    USER_NOT_FOUND: "User not found.",
    INVALID_CREDENTIALS: "Invalid credentials. Please try again.",
    USER_REGISTERED: "User SignUp successfully.",
    LOGIN_SUCCESS: "Login successful.",
    LOGIN_FAILED: "Login failed. Invalid credentials.",
    ACCESS_DENIED: "Access denied. You do not have permission.",
    SOMETHING_WENT_WRONG: "Something went wrong. Please try again later.",
    RESOURCE_CREATED: "Resource created successfully.",
    RESOURCE_UPDATED: "Resource updated successfully.",
    RESOURCE_DELETED: "Resource deleted successfully.",
    RESOURCE_NOT_FOUND: "Resource not found.",
    DUPLICATE_ENTRY: "Duplicate entry. The resource already exists.",
    VALIDATION_ERROR: "Validation error. Please check your input.",
    USER_DETAILS_FETCHED:"User Details Fetched.",
    USER_DETAILS_FETCHED_FAILED :"User detailes fetched failed",
    OTP_SENT:"Otp is sent in your registered email.",
    USER_SUBJECT_FOR_EMAIL:"Your Otp for generating new password",
    USER_DETAILS_FETCHED:"User Details fetched successfully",
    USER_PASSWORD_RESET_SUCCESSFULL:"User password reset successfull",
    USER_PASSWORD_UPDATED_SUCCESSFULL:"User password updated successfully",
    IN_CORRECT_OTP:"Please entere the correct OTP",
    EMPTY_DATA:"",
    FILED_TO_FETCH_USER_USER_DETAILS:"Failed to fetch user details",
    USER_UPDATED_SUCCESSFULLY:"User Updated Successfully.",
    SOFT_USER_DELETED:"Your account is not longer exist.",
    SALT:10,
    FOLLOW_SUCCESS :"Follow Success",
    FOLLOW_FAIL:"Follow Fail",
    UNFOLLOW_SUCCESSFULLY :"Unfollow Successfully",
    UNFOLLOW_FAIL :"Unfollow Fail",
    GET_FOLLOWING_LIST_SUCCESS: "Following Users list fetch successfully",
    GET_FOLLOWING_LIST_FAIL: "Following Users list fetch fail",
    GET_FOLLOWER_LIST_SUCCESS:"Follower List fetch successfully",
    GET_FOLLOWER_LIST_FAILED:"Follower List Fialed",
    USER_DETAILS_FETCHED_SUCCESSFULLY:"User details fetched successfully",
    USER_DETAILS_FETCHED_FAIL:"User details fetched Fail",
    USER_NAME_NOT_EXIST:"This user name does not exist.",
    INDIVIDUAL_USER_DETAILS_GET_SUCCESSFULLY:"User Details get successfully.",
    INDIVIDUAL_USER_DETAILS_GET_FAIL:"User Details get fail.",
    ZERO:0,
    NO_JOURNEY_DETAILS_FOR_THIS_USER :"No journey created by this user",
    YOU_HAD_BLOCKED_THIS_PERSON_SUCCESSFULLY:"You had blocked this person successfully",
    YOU_HAD_BLOCKED_THIS_PERSON_FAIL:"You had blocked this person fail",
    YOU_CONNOT_BLOCK_YOUR_SELF:"You cannnot block your self.",
    YOU_JUST_UNBLOCK_THIS_PERSON:"You just unblock this person",
    UNBLOCK_FAIL:"Unblock fail",
    BLOCKED_USERS_LIST_FETCH_SUCCESSFULLY : "Blocked users fetch successfully",
    BLOCKED_USERS_LIST_FETCH_FAIL : "Blocked users fetch fail",
    USER_REPORTED_SUCCESSFULLY:"User Reported successfully",
    USER_REPORTED_FAIL:"User Reported Fail",
    BLOCKED_USER:"You had blocked this user",
    REPORTER_LIST_FETCH_SUCCESSFULLY:"Reporter list fetch successfully.",
    REPORTER_LIST_FETCH_FAIL:"Reporter list fetch Fail.",
    JOURNEY:"journey",
    USER:"user",
    TIMELINE:"timeline",
    YOU_HAD_ALREADY_CREATED_REPORT_FOR_THIS_USER:"You had already created report for this user.",
    YOU_CANNOT_REPORT_YOURSELF :"You are not able to report yourself"
  };
  
  export default userConstantMessages;
  